AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Outputs the time
Resources:
  TimeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs4.3
      CodeUri: ./lambdafn/
      Events:
        MyTimeApi:
          Type: Api
          Properties:
            Path: /TimeResource
            Method: GET

  SpacefinderFn:
    Type: AWS::Serverless::Function
    Properties:
      Handler: locations.Get
      Runtime: nodejs4.3
      CodeUri: ./SpacefinderFn/
      Events:
        SpacefinderAPI:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /locations
            Method: Get


  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
        DefinitionUri: ./swagger/SpacefinderAPI.yml
        StageName: Prod
        Variables:
          # NOTE: Before using this template, replace the <<region>> and <<account>> fields
          #       in Lambda integration URI in the swagger file to region and accountId 
          #       you are deploying to
          LambdaFunctionName: !Ref LambdaFunction
Outputs:
  ApiUrl:
    Description: URL of your API endpoint
    Value: !Join
      - ''
      - - https://
        - !Ref ApiGatewayApi
        - '.execute-api.'
        - !Ref 'AWS::Region'
        - '.amazonaws.com/Prod