AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Outputs the time
Resources:
  TimeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs4.3
      CodeUri: ./lambdafn/
      Events:
        MyTimeApi:
          Type: Api
          Properties:
            Path: /TimeResource
            Method: GET

  locationsfn:
    Type: AWS::Serverless::Function
    Properties:
      Handler: locations.Get
      Runtime: nodejs4.3
      CodeUri: ./spacefinderfn/
      Events:
        GetLocations:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /locations
            Method: GET
  locationscreatefn:
    Type: AWS::Serverless::Function
    Properties:
      Handler: locations.Create
      Runtime: nodejs4.3
      CodeUri: ./spacefinderfn/
      Events:
        PostLocations:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /locations
            Method: POST
  locationsgetfn:
    Type: AWS::Serverless::Function
    Properties:
      Handler: locations.Get
      Runtime: nodejs4.3
      CodeUri: ./spacefinderfn/
      Events:
        PostLocations:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /locations/{locationId}
            Method: GET
  locationsdeletefn:
    Type: AWS::Serverless::Function
    Properties:
      Handler: locations.Delete
      Runtime: nodejs4.3
      CodeUri: ./spacefinderfn/
      Events:
        PostLocations:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /locations/{locationId}
            Method: POST  
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
        DefinitionUri: ./swagger/SpacefinderAPI.yaml
        StageName: prod
        #Variables:
        #  LocationsFn: !Ref locationsfn
        #  LocationsCreateFn: !Ref locationscreatefn
          #LocationsGetFn: !Ref locationsgetfn
          #LocationsDeleteFn: !Ref locationsgdeletefn

Outputs:
  ApiUrl:
    Description: URL of your API endpoint
    Value: !Join
      - ''
      - - https://
        - !Ref ApiGatewayApi
        - '.execute-api.'
        - !Ref 'AWS::Region'
        - '.amazonaws.com/Prod'